site_name: 极光文档
site_author: JPush Offical
site_url: http://docs.jpush.io
site_favicon: favicon.ico
site_description: JPush, JMessage, 极光推送, 极光IM, Android Push, Android 推送, 安卓推送, iOS Push, APNs, Push Notification
copyright: Copyright 2011-2016, jiguang.cn, All Rights Reserved. <br />粤ICP备12056275号-5 深圳市和讯华谷信息技术有限公司
theme: readthedocs

pages:
-  JPush 文档: 'index.md'

- 入门指南:
  - '常见问题': 'guideline/faq.md'
  - 'JPush Android 集成指南': 'guideline/android_guide.md'
  - 'JPush iOS 集成指南': 'guideline/ios_guide.md'
  - 'JPush WinPhone 集成指南': 'guideline/winphone_guide.md'
  - '3 分钟集成 Android SDK': 'guideline/android_3m.md'
  - '示例与代码': 'guideline/sample_code.md'
  - '控制台使用指南': 'guideline/statistical_report.md'
  - '短信验证': 'guideline/JSMS_guide.md'
  - 'Android 短信验证集成指南': 'guideline/Android_SMS_SDK.md'
  - 'iOS 短信验证集成指南': 'guideline/iOS_SMS_SDK.md'

- 客户端:
  - 'Android SDK 概述': 'client/android_sdk.md'
  - 'Android SDK 教程': 'client/android_tutorials.md'
  - 'Android SDK API': 'client/android_api.md'
  - 'iOS SDK 概述': 'client/ios_sdk.md'
  - 'iOS SDK 教程': 'client/ios_tutorials.md'
  - 'iOS SDK API': 'client/ios_api.md'
  - 'WinPhone SDK 概述': 'client/winphone_sdk.md'
  - 'WinPhone SDK API': 'client/winphone_api.md'
  - '客户端集成插件': 'client/client_plugins.md'

- 服务器端:
  - '服务器端 概述': 'server/server_overview.md'
  - 'REST API v3 - Push': 'server/rest_api_v3_push.md'
  - 'REST API v3 - Report': 'server/rest_api_v3_report.md'
  - 'REST API v3 - Device': 'server/rest_api_v3_device.md'
  - 'REST API v3 - Schedule': 'server/rest_api_push_schedule.md'
  - 'REST API v2 - Push': 'server/rest_api_v2_push.md'
  - 'REST API v2 - Report': 'server/rest_api_v2_report.md'
  - '短信 REST API': 'server/rest_api_jsms.md'
  - 'HTTP 状态码': 'server/http_status_code.md'
  - 'Java SDK': 'server/java_sdk.md'
  - 'Python SDK': 'server/python_sdk.md'
  - 'PHP SDK': 'server/php_sdk.md'
  - 'Ruby SDK': 'server/ruby_sdk.md'
  - 'C# SDK': 'server/csharp_sdk.md'
  - 'Node.js SDK': 'server/nodejs_sdk.md'

- 高级:
  - 'JPush应用场景': 'advanced/scenes.md'
  - 'JPush高级话题': 'advanced/topics.md'
  - 'Rich Push 入门指南': 'advanced/rich_push.md'
  - 'JMessage高级话题': 'advanced/jmessage_topics.md'

- 更多:
  - '使用许可协议': 'more/use_license.md'
  - '联系我们': 'more/contact_us.md'

- 最近更新: 'updates.md'

- 资源下载:
  - JPush: 'resources.md'
